traducao_paises = {
    'US': 'Estados Unidos',
    'SG': 'Singapura',
    'BG': 'Bulgária',
    'CH': 'Suíça',
    'EG': 'Egito',
    'CA': 'Canadá',
    'MX': 'México',
    'NZ': 'Nova Zelândia',
    'JP': 'Japão',
    'IL': 'Israel',
    'AU': 'Austrália',
    'CZ': 'República Tcheca',
    'IT': 'Itália',
    'DZ': 'Argélia',
    'KR': 'Coreia do Sul',
    'RU': 'Rússia',
    'FR': 'França',
    'DE': 'Alemanha',
    'IE': 'Irlanda',
    'PT': 'Portugal',
    'NO': 'Noruega',
    'SE': 'Suécia',
    'GB': 'Reino Unido',
    'UA': 'Ucrânia',
    'PL': 'Polônia',
    'BR': 'Brasil',
    'NL': 'Holanda',
    'CL': 'Chile',
    'BE': 'Bélgica',
    'HK': 'Hong Kong',
    'LT': 'Lituânia',
    'LV': 'Letônia',
    'ID': 'Indonésia',
    'AD': 'Andorra',
    'AT': 'Áustria',
    'KE': 'Quênia',
    'NG': 'Nigéria',
    'EE': 'Estônia',
    'TR': 'Turquia',
    'ES': 'Espanha',
    'ZA': 'África do Sul',
    'FI': 'Finlândia',
    'GR': 'Grécia',
    'IN': 'Índia',
    'LU': 'Luxemburgo',
    'RO': 'Romênia',
    'AR': 'Argentina',
    'SK': 'Eslováquia',
    'TH': 'Tailândia',
    'HU': 'Hungria',
    'TW': 'Taiwan',
    'EC': 'Equador'
}